# Generated by Django 5.0.3 on 2024-04-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('national_code', models.IntegerField()),
                ('expert', models.CharField(choices=[('REZA', 'Reza')], max_length=10)),
            ],
        ),
    ]
