# Generated by Django 5.0.3 on 2024-05-25 10:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_person_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='person',
            name='expert',
            field=models.CharField(choices=[('ali asadi', 'Expert1'), ('reza rahimi', 'Expert2'), ('amir kashefi', 'Expert3')], max_length=200, verbose_name='Expert'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a 10-digit number.')], verbose_name='National Code'),
        ),
    ]
