# Generated by Django 5.0.3 on 2024-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_person_created_at_alter_person_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=0, verbose_name='Birth Date'),
            preserve_default=False,
        ),
    ]
