# Generated by Django 5.0.3 on 2024-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(verbose_name='Birth Date'),
        ),
    ]
