# Generated by Django 5.0.3 on 2024-05-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
