# Generated by Django 5.0.3 on 2024-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_person_created_at_alter_person_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default=1, max_length=30, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.CharField(default=0, max_length=30, verbose_name='Province'),
            preserve_default=False,
        ),
    ]
