# Generated by Django 5.0.3 on 2024-05-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_person_city_person_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='province',
        ),
    ]
