# Generated by Django 5.0.3 on 2024-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_person_city_remove_person_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default=0, max_length=30, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.CharField(default=12, max_length=30, verbose_name='Province'),
            preserve_default=False,
        ),
    ]
