# Generated by Django 5.0.3 on 2024-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_person_created_at_alter_person_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province'),
        ),
    ]
